name: Minh's Notebook
description: Hi there, welcome to my blog. I am a guy who is striving for knowledge and trying to learn as much as I can everyday. This is a place I store the interesting things I found on that path. Happy reading and don't hesitate to leave me some comments 💪
meta_description: "Minh's Notebook"

aboutPage: true
markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
baseurl: /
rooturl: https://minh.guru
domain_name: 'nguyenquangminh0711.github.io'

#facebook_comments: 733223113511154
disqus_comments: true
google_analytics: 'UA-92088150-1'

# Details for the RSS feed generator
author: "Minh's notebook"

permalink: /:year/:month/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
