# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal blog of Nguyen Quang Minh
email: nguyenquangminh0711@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for me to share the knowledges I collected.
  A place for me to express myself.
  A place for me to have fun :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "nguyenquangminh0711.github.io" # the base hostname & protocol for your site
github_username:  nguyenquangminh0711
timezone: Asia/Ho_Chi_Minh
permalink: none
paginate: 10

category_dir: ""
category_title_prefix: ""

gems: [jekyll-paginate]
markdown: kramdown
