name: nguyenquangminh0711
description: Research. Code. Follow my passion.
meta_description: "nguyenquangminh0711 - Research. Code. Follow my passion."

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'nguyenquangminh0711.github.io'

facebook_comments: 733223113511154

# Details for the RSS feed generator
author:         'nguyenquangminh0711'

permalink:       /:year/:month/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
